### ISSUE TITLE
disable-services.ps1 problem with Chrome and Facebook browsing

### ISSUE THREAD

**Issue by BoQsc** [W4RH4WK/Debloat-Windows-10#116] opened 2017-05-11 12:44 UTC
**Still not sure everything what is bad leads to only this script.**

Operating system: Initialy installed Windows 10 + windows updates up until 2017-05-11

Applying whole disable-services.ps1 script leads to unstable browsing in facebook videos and other places using chrome.

Details while browsing Facebook using Chrome: 
- Chrome not responding
- Sudden stop of the video playback.
- Random crashing of the facebook webpage.

**Comment by W4RH4WK** [comment] 2017-11-02 08:14
Sorry for immediately answering this issue. I was not able to reproduce the problems you encountered.

Since no-one else mentioned similar issues I'd close this for now in the hope that problems were not caused by the scripts. Let me know if you managed to narrow it down.

**Closed** 2017-11-02 08:15 UTC
